### ISSUE TITLE
Filter Effects Module Level 1

### ISSUE THREAD

**Issue by i-akhmadullin** [i-akhmadullin/Sublime-CSS3#19]
http://www.w3.org/TR/filter-effects/

``` css
@filter red {
    src: url('simple.vs') format('x-shader/x-vertex'), url(simple.fs) format('x-shader/x-fragment');
}
#filtered-element {
    filter: custom(red);
}
```
