### ISSUE TITLE
CSS Image Values and Replaced Content Module Level 3

### ISSUE THREAD

**Issue by i-akhmadullin** [i-akhmadullin/Sublime-CSS3#29]
http://www.w3.org/TR/css3-images/

``` css
.css3-images {
    object-fit: fill | contain | cover | none | scale-down;
    object-position: 50% 50%;
    image-orientation: 90deg;
    image-resolution: [from-image || <resolution>] && snap?;
    background: image('sprites.svg#xywh=40,0,20,20');
}
```
