### ISSUE TITLE
CSS Fonts Module Level 3

### ISSUE THREAD

**Issue by i-akhmadullin** [i-akhmadullin/Sublime-CSS3#31]
http://www.w3.org/TR/css3-fonts/

``` css
.s {
font-kerning: auto | normal | none;
font-variant-ligatures: normal | none | [ <common-lig-values> || <discretionary-lig-values> || <historical-lig-values> || <contextual-alt-values> ];
}
```
